version: "3.1"

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pptppt
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_PORT: 8001
    ports:
      - "8001:80"
    depends_on:
      - postgres
volumes:
  postgres-data:
